#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home: /
  Archives: archives
  Topics: categories
  CV: cv
  Portfolio: portfolio
  About: about
rss: /atom.xml

# Sidebar
widgets:
  #- profile
  #- social
  #- recent_posts
  #- category
  #- archive

# Widget Options
archive_type: 'monthly'
show_count: true

# Profile Picture - place inside /source/img
# Only shows up if profile enabled in widgets
profile: /img/profile.jpg

# Social Links
# Key is Font Awesome icon name, value is target link
# See Font Awesome icons at: https://fontawesome.com/icons?d=gallery
social:
  LinkedIn-In: https://www.linkedin.com/in/michaelthanh/
  Github: https://github.com/mvxt
  Medium-M: https://medium.com/@michael.thanh
  Youtube: https://www.youtube.com/channel/UCD9Vpco6dO5GfYOSmipwlvg
  Twitter: https://twitter.com/mikeyvxt

# Search
search:
  insight: true # Install `hexo-generator-json-content` before using Insight Search

# HTML Page Metadata
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
favicon: favicon.ico
google_site_verification:

