#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home / 主页: /
  Archives / 存档: archives
  Topics / 主题: categories
  CV: cv
  Projects: projects 
  Ethos: ethos
  About / 关于: about
rss: /atom.xml

# Sidebar
widgets:
  # - profile
  # - social
  - recent_posts
  - category
  - archive

# Widget Options
archive_type: monthly
show_count: true

# Profile Picture - place inside /source/img
# Only shows up if profile enabled in widgets
profile: /img/profile.jpg

# Social Links
# Key is Font Awesome icon name, value is target link
# See Font Awesome icons at: https://fontawesome.com/icons?d=gallery
social:
#   LinkedIn-In: https://www.linkedin.com/in/michaelthanh/
#   facebook: https://www.linkedin.com/in/michaelthanh/
   Github: https://github.com/magicnue
#    Medium-M: https://medium.com/@michael.thanh
#   Twitter: https://twitter.com/mikeyvxt

# Search
search:
  insight: true # Install `hexo-generator-json-content` before using Insight Search

# HTML Page Metadata
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
favicon: img/UN-logo.svg
google_site_verification: FHK_lhsTlcLbPDI5IkA4bjEvJ2R6JzO66YFIP83rNwg

