home: Home
archives: Archives
about: About
categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Previous
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
share: Share
theme_by: Modified from theme by
rss_feed: RSS Feed
category: Category
tag: Tag
connect: 'Connect With Us'
post_total_count_one: 共计 %d 篇文章.
post_total_count: 共计 %d 篇文章.
categories_total_count_one: 共计 about %d 个话题.
categories_total_count: 共计 about %d 个话题.
read_more: Continue Reading →
contents: Contents
none: None
insight:
    hint: 'Type something...'
    posts: 'Posts'
    pages: 'Pages'
    categories: 'Categories'
    tags: 'Tags'
    untitled: '(Untitled)'
